In [1]:
# creating an in-memory SQLite Database and loading the necessary datasets

import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

In [ ]:
# 1. Count the total number of medals won by each country and show the top 5

pd.read_sql("""
SELECT * FROM athletes_table;
            """, conn)

pd.read_sql("""
SELECT Team, COUNT(Medal) AS Total_Medals
FROM athletes_table
WHERE Medal IS NOT NULL
GROUP BY Team
ORDER BY Total_Medals DESC
LIMIT 5;
            """,conn)

            Team  Total_Medals
0  United States          5219
1   Soviet Union          2451
2        Germany          1984
3  Great Britain          1673
4         France          1550

In [ ]:
# 2. Calculate the average age of athletes who won a Gold medal
pd.read_sql("""
SELECT * FROM athletes_table;
            """, conn)
pd.read_sql("""
SELECT AVG(Age), Medal
FROM athletes_table
WHERE Medal = "Gold";
            """, conn)

    AVG(Age) Medal
0  25.901013  Gold

In [27]:
# 3. How many distinct events are there in each sport?
pd.read_sql("""
SELECT * FROM athletes_table;
            """, conn)

pd.read_sql("""
SELECT Sport, COUNT(DISTINCT Event) AS Event_Count
FROM athletes_table
GROUP BY Sport
ORDER BY Event_Count DESC
LIMIT 10;
            """, conn)

              Sport  Event_Count
0          Shooting           83
1         Athletics           83
2          Swimming           55
3           Cycling           44
4           Sailing           38
5         Wrestling           30
6  Art Competitions           29
7           Archery           29
8        Gymnastics           27
9          Canoeing           27

In [31]:
# 4. Show all athletes from the United States (NOC = 'USA').
pd.read_sql("""
SELECT * FROM athletes_table;
            """, conn)
pd.read_sql("""
SELECT DISTINCT Name, Sport, Event, NOC
FROM athletes_table
WHERE NOC = "USA";
            """, conn)

,Name,Sport,Event,NOC
0,Per Knut Aaland,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,USA
1,Per Knut Aaland,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,USA
2,Per Knut Aaland,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,USA
3,Per Knut Aaland,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,USA
4,Per Knut Aaland,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,USA
...,...,...,...,...
14735,Rami Zur,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",USA
14736,Rami Zur,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",USA
14737,Rami Zur,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",USA
14738,"Victor Andrew ""Vic"" Zwolak",Athletics,"Athletics Men's 3,000 metres Steeplechase",USA
14739,"James Francis ""Jim"" Zylker",Football,Football Men's Football,USA

In [33]:
# 5. Count how many medals were awarded each year.
pd.read_sql("""
SELECT * FROM athletes_table;
            """, conn)

pd.read_sql("""
SELECT Year, COUNT(Medal)
FROM athletes_table
GROUP BY Year;
""", conn
)

    Year  COUNT(Medal)
0   1896           143
1   1900           604
2   1904           486
3   1906           458
4   1908           831
5   1912           941
6   1920          1308
7   1924           962
8   1928           823
9   1932           739
10  1936          1025
11  1948           987
12  1952          1033
13  1956          1043
14  1960          1058
15  1964          1215
16  1968          1256
17  1972          1414
18  1976          1531
19  1980          1602
20  1984          1698
21  1988          1845
22  1992          2030
23  1994           331
24  1996          1842
25  1998           440
26  2000          2004
27  2002           478
28  2004          2001
29  2006           526
30  2008          2048
31  2010           520
32  2012          1941
33  2014           597
34  2016          2023

In [35]:
# 6. Find all athlete records where height or weight is missing

pd.read_sql("""
SELECT *
FROM athletes_table
WHERE height IS NULL OR weight IS NULL;
""", conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,None
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None

In [40]:
# 7. Replace the missing height with the average athlete height.
pd.read_sql("""
SELECT * FROM athletes_table;
""", conn)

pd.read_sql("""
SELECT *,
COALESCE(height, (SELECT AVG(height) FROM athletes_table)) AS height_values
FROM athletes_table
WHERE height IS NULL;
""", conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,height_values
0,3,Gunnar Nielsen Aaby,M,24.0,None,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None,175.33897
1,4,Edgar Lindenau Aabye,M,34.0,None,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,175.33897
2,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,None,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None,175.33897
3,15,Arvo Ossian Aaltonen,M,22.0,None,NaN,Finland,FIN,1912 Summer,1912,Summer,Stockholm,Swimming,Swimming Men's 200 metres Breaststroke,None,175.33897
4,15,Arvo Ossian Aaltonen,M,22.0,None,NaN,Finland,FIN,1912 Summer,1912,Summer,Stockholm,Swimming,Swimming Men's 400 metres Breaststroke,None,175.33897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60166,135539,Marius Edmund Zwiller,M,18.0,None,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None,175.33897
60167,135542,Werner Zwingli,M,29.0,None,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None,175.33897
60168,135542,Werner Zwingli,M,29.0,None,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None,175.33897
60169,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,None,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None,175.33897
60170,135561,Frantiek Zyka,M,26.0,None,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None,175.33897

In [57]:
# 8. Return total sales value per item
pd.read_sql("""
SELECT * FROM sales_table
            """, conn)

#pd.read_sql("""
           # SELECT order_id, item_name, CAST(REPLACE(item_price, "$"," ") AS REAL) * quantity AS total_sales
           # FROM sales_table
           # GROUP BY item_name
           # ORDER BY total_sales DESC;
           # """, conn)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,None,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [59]:
# 9. Show the top 5 records with the highest item_price
pd.read_sql("""
            SELECT * FROM sales_table;
            """, conn)

pd.read_sql("""
            SELECT item_name, choice_description, item_price
            FROM sales_table
            ORDER BY item_price DESC
            LIMIT 5;
            """, conn)

,item_name,choice_description,item_price
0,Steak Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$9.39
1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
2,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
3,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.39
4,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$9.39

In [69]:
# 10. How many unique customer orders are there? (Assume each order_id is a customer.)
pd.read_sql("""
            SELECT * FROM sales_table;
            """, conn)
pd.read_sql("""
            SELECT COUNT(DISTINCT order_id) AS Total_Unique_Orders 
            FROM sales_table;
            """, conn)

   Total_Unique_Orders
0                 1834

In [ ]:
# Section 2
#Write one query for this section.

# Find countries with high-performing athletes in the Olympics. Use at least JOIN, NESTED QUERY, CASE, and optionally WITH.
# For each country:
# Count the number of athletes who won at least one medal.
# Determine the average age of those medalists.
# Create a new column called performance:
# 'High' if average age is below 25
# 'Medium' if between 25 and 30
# 'Low' if above 30

In [9]:
pd.read_sql("""
            SELECT * FROM regions_table
            """, conn)
pd.read_sql("""
SELECT
    region,
    athletesperformers,
    Avg_Age,
    CASE
        WHEN Avg_Age < 25 THEN 'High'
        WHEN Avg_Age BETWEEN 25 AND 30 THEN 'Medium'
        ELSE 'Low'
    END AS performance
FROM
(
    SELECT
        r.region,
        COUNT(DISTINCT a.Name) AS athletesperformers,
        AVG(a.Age) AS Avg_Age
    FROM athletes_table a
    JOIN regions_table r
        ON a.NOC = r.NOC
    WHERE a.Medal IS NOT NULL
    GROUP BY r.region
) AS medalists
ORDER BY athletesperformers DESC;
""", conn)

                 region  athletesperformers    Avg_Age performance
0                   USA                3836  24.896638        High
1                Russia                2607  25.286765      Medium
2               Germany                2563  25.464410      Medium
3                    UK                1601  27.846310      Medium
4                France                1277  27.982153      Medium
..                  ...                 ...        ...         ...
131               Sudan                   1  23.000000        High
132            Suriname                   1  22.000000        High
133                Togo                   1  27.000000      Medium
134               Tonga                   1  26.000000      Medium
135  Virgin Islands, US                   1  27.000000      Medium

[136 rows x 4 columns]